# Generated by Django 5.1.3 on 2024-11-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaignresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
