# Generated by Django 5.1.3 on 2024-11-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_campaign_campaing_type_campaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaignresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
